### ISSUE TITLE
Improve license information

### ISSUE THREAD

**Issue by fmlrt** [cafienne/bounded-framework#10]
There are several things related to project licensing that could be improved

1. Amount of boilerplate code
Apache 2.0 license does not require each file to contain a lot of license text. It may vary from no notice on the individual file level to short notice to elaborate notice if one wants each file read in isolation to point to the origins of it.

2. Clear  reference to the owner(s)
Currently it states:
```
// Copyright (C) 2018 the original author or authors.
// See the LICENSE file distributed with this work for additional
// information regarding copyright ownership.
```
`original author or authors` is not elaborated on anywhere else

Good example of succinct header addressing both points IMHO is akka project:
```
/**
 * Copyright (C) 2009-2018 Lightbend Inc. <https://www.lightbend.com>
 */
```

Another possibility is to include reference to owner and site in `README.md` once and not to each individual file, which is also sufficient by Apache 2.0 license if one wishes.

**Comment by olger** [comment]
I'd prefer todo the Lightbend style, although I wonder what the effect of that is with regards to individual contributors as named in the apache 2 license.

**Comment by fmlrt** [comment]
If I understand it correctly it is enough to mention individual contributors within commit messages if one commits changes heavily influenced by collaboration or as result of applying patch file.

In case merge is performed in a way that retains original author of commit(s) nothing else needed.

And it can be mentioned in file header too. But we'd need to amend style check a bit.

There are almost no examples on the internet about this. Best story I could find is OpenSSL re-licensing https://www.coreinfrastructure.org/news/announcements/2017/03/openssl-re-licensing-apache-license-v-20-encourage-broader-use-other-foss, https://www.openssl.org/blog/blog/2015/08/01/cla/, https://license.openssl.org/, https://www.openssl.org/blog/blog/categories/license/
Especially interesting part of story is about removing code because of contributor's disagreement with re-licensing.
