### ISSUE TITLE
Create example with CommandGateway

### ISSUE THREAD

**Issue by wketting** [cafienne/bounded-framework#19]
Bounded has a CommandGateway defined, but in the Cargo example the CommandGateway is not used, instead another class, JobAggregateRootRouterProvider, is being used. This does not match with the rest of the sample project (gives errors). It would be nice if JobAggregateRootRouterProvider is adjusted or replaced by CommandGateway (derived) class.

**Comment by olger** [comment]
Agreed, working on a sample in cargo and a proper working gateway, expect a pull request soon

**Comment by olger** [comment]
Closed by work in #19
