### ISSUE TITLE
Introduce projections model with implementation based on eventmaterializers

### ISSUE THREAD

**Issue by efemelar** [cafienne/bounded-framework#9]
This is proposal to adopt widely used notion of Projection in place where EventMaterializer is used. 
Reason is that it would help with on-boarding by requiring to keep less of a mapping between concepts discussed in DDD/CQRS/ES circles and concrete implementation found in `bounded-framework`.

Current toolkit from `io.cafienne.bounded.akka.persistence.eventmaterializers` would become akka-persistence implementation.

**Comment by olger** [comment]
Sounds like a good plan, it's better to have the naming inline with community.

Let's discuss a bit on the naming, what the effect will be and package naming.

**Comment by fmlrt** [comment]
Using `i.c.b` as a short for `io.cafienne.bounded` it might be something like:

- `i.c.b.projection`
for API entry point, generic definitions, factory methods etc
there would go `Resumable`, `ResumableReplayable`, generic bits of `AbstractEventMaterializer`, `OffsetType`

- `i.c.b.projection.inmem`, `i.c.b.projection.cassandra`, `i.c.b.projection.jdbc` etc
for persistence mechanism dependent details of storing data & offsets in safe way, batching, etc

- `i.c.b.projection.source`
for journal selection based on config, syntactic niceties on top of akka's `ReadJournal` API, with possible sub-packages if we to implement sources which go around akka's API
  
Does it make sense so far? Have I missed something important?

**Comment by olger** [comment]
Makes clearly sense. If you have an idea on this structure and the naming, please make a pull request for that. (let's first process open pull requests in order to prevent heavy merge issues though)
